import "../../assets/css/histoire_art.scss"
import { Link } from "react-router-dom"
const HistoireDeLart = () => {
    const events = [
        {date: '-4 000/-480', name: 'Art Egyptien', link: 'egypte-antique', subtitle: "Art Antique Egyptien", short: "L'art de l'Égypte antique apparait dès les premiers signes de la culture de Nagada, vers 3800 avant l'ère commune. Certains traits, caractéristiques à une époque, peuvent s'atténuer ou disparaitre à une autre. Mais un grand nombre de ces caractères se sont maintenus sur la très longue durée de l'histoire de l'Égypte antique, jusqu'à la fin de l'Empire lagide, en 30 AEC, avec les derniers des 345 pharaons."},
        {date: '-1 000/-100', name: 'Art Grec', link: 'grec-antique', subtitle: "Art Antique Grec", short: "L'art de la Grèce antique a exercé une influence considérable sur la culture de nombreux pays des temps anciens à nos jours, en particulier dans les domaines de la sculpture et de l'architecture. À l'ouest, l'art de l'Empire romain s'est largement inspiré des modèles grecs. À l'est, les conquêtes d'Alexandre le Grand ont permis plusieurs siècles d'échanges entre les Grecs, l'Asie centrale et les cultures indiennes, ce qui a donné naissance à l'art gréco-bouddhique, avec ses ramifications jusqu'au Japon lui-même."},
        {date: '-753/395', name: 'Art Romain', link: 'rome-antique', subtitle: "Art Romain Antique", short: "L'art romain est l'art produit dans les territoires de la Rome antique, depuis la fondation de Rome jusqu'à la chute de l'Empire d'occident. Il prend un véritable essor au contact de l'art grec que les historiens de l'art, au XIXᵉ siècle, lui reprocheront d'imiter, et trouve de nouvelles influences dans les régions soumises par l'Empire. Après la chute de l'Empire, l'art romain se prolonge dans l'art byzantin et l'art chrétien médiéval."},
        {date: '10ᵉ/11ᵉ', name: 'Art Roman', link: 'roman', subtitle: "l'Art Roman au service de la Religion", short: "En histoire de l'art, la période de l'art roman est celle qui s'étend du début du XIᵉ siècle à la seconde moitié du XIIᵉ siècle, entre l'art préroman et l'art gothique, en Europe. L'expression « art roman » est forgée en 1818 par l'archéologue français Charles de Gerville et passe dans l'usage courant à partir de 1835. L'art roman regroupe aussi bien l'architecture romane que la sculpture, la peinture ou la statuaire romane de la même époque."},
        {date: '12ᵉ/15ᵉ', name: 'Art Gothique', link: 'gothique', subtitle: "Primitif, Rayonnant, Flamboyant", short: "L'art gothique, autrefois appelé art français ou art ogival, est une période de l'art européen qui s'étend du milieu du XIIᵉ siècle au début du XIVᵉ siècle. Il est précédé par l'art roman, dont il est à ses débuts un prolongement, et suivi par l'art de la Renaissance. Apparu en Île-de-France, il se diffuse rapidement au reste de l'Europe occidentale."},
        {date: '15ᵉ/16ᵉ', name: 'Renaissance Italienne', link: 'renaissance-italienne', subtitle: "Rupture avec le Moyen Âge", short: "Influencée par les traditions Antiques, l'ouverture et l'élégance remplacent le besoin de protection guerrier du Moyen Age. La protection des grandes familles et l'invention de l'imprimerie, en 1436, permettent le développement des arts."},
        {date: '15ᵉ/16ᵉ', name: 'Renaissance Francaise', link: 'renaissance-française', subtitle: "Rupture avec le Moyen Âge", short: "La Renaissance française est un mouvement artistique et culturel situé en France entre le milieu du XVᵉ siècle et le début du XVIIᵉ siècle. Étape de l'époque moderne, la Renaissance apparaît en France après le début du mouvement en Italie et sa propagation dans d'autres pays européens."},
        {date: '1589/1650', name: 'Style Louis XIII', link: 'louis-XIII', subtitle: "Style de transition", short: "Caractéristique d'une période de transition entre le style Renaissance et le style baroque dont il assimile progressivement les influences italienne, espagnole et flamande, il a inspiré à la fin du XIXe siècle et au début du XXe siècle, le style néo-Louis XIII1."},
        {date: '1650/1715', name: 'Style Louis XIV', link: 'louis-XIV', subtitle: "Richesse et Majestée", short: "Le style Louis XIV est un style d'ameublement couvrant plus ou moins la période du règne de Louis XIV (1661 à 1715). Ce style est caractérisé par la majesté et la richesse de son mobilier. C'est pendant cette période que la technique de marqueterie dite « marqueterie Boulle » est développée."},
        {date: '1715/1723', name: 'Style Régence', link: 'regence', subtitle: "L'art Versaillais du régent Philippe III d’Orléans", short: "Sous la Régence, les aristocrates proches de la cour recherchent plus d'intimité et de raffinement, plus de soirées à thème (lecture, orchestres, etc.). Des salons se tiennent dans lesquels on rencontre des écrivains, des poètes, des philosophes. Le thème de l'amour rencontre un vif succès. On met en avant la galanterie : éducation et esprit. C'est également la période de la commedia dell'arte."},
        {date: '1723/1755', name: 'Style Louis XV', link: 'louis-XV', subtitle: "Style d'invention, pied galbé, asymétrie", short: "Le style Louis XV est initialement un style caractéristique de sièges, qui a ensuite influencé tous les arts de son époque. Ce style qui puise une partie de son inspiration dans la nature se caractérise par sa légèreté et une recherche de l'intimité et du confort. Succédant au style Régence, le style Louis XV se développe essentiellement dans le deuxième quart du XVIIIe siècle (1723-1750). De nombreux ouvrages font référence à ce style sous le nom de rocaille ou rococo, surtout quand il s'agit de projets complets de décoration intérieure faits par des ornemanistes."},
        {date: '1750/1789', name: 'Style Transition Louis XVI', link: 'louis-XV', subtitle: "Style d'invention, pied galbé, asymétrie", short: "Le style Louis XVI s'échelonne de 1750 à 1789 environ. Influencé par les fouilles des villes d'Herculanum en 1711, mais surtout par Pompeï en 1748. C'est Madame De Pompadour qui fût à l'origine d'une mission en Italie pour étudier l'art antique."},
        {date: '1789/1804', name: 'Style Directoire', link: 'directoire', subtitle: "Transition entre Louis XVI et l'Empire", short: "Le style Directoire est un style d'ameublement et de décoration en vogue de 1789 à 1803. Marquant la transition entre les styles Louis XVI et Empire, il se caractérise par une facture sobre, des formes simples et l'apparition de certains thèmes décoratifs."},
        {date: '1804/1815', name: 'Style Empire', link: 'empire', subtitle: "Le style Empire est un style d'ameublement et de décoration néo-classique inspiré par Napoléon Ier et ses campagnes militaires", short: "Le style Empire est un style d'ameublement et de décoration en vogue de 1803 (après les campagnes d'Égypte et d'Italie) à 1821. Il succède au style Directoire et précède le style Restauration. Conçu par les architectes Charles Percier et Pierre Fontaine, il prend son essor sous les directives de Napoléon Ier, et perdure après son abdication. Par extension il désigne aussi des œuvres architecturales, dont les monuments impériaux, et l'art de propagande produit sous Napoléon Ier en peinture et en sculpture."},
        {date: '1815/1830', name: 'Style Restauration', link: 'restauration', subtitle: "Règnes de Louis XVIII et Charles X", short: "Le style Restauration, contemporain du Biedermeier qui fleurit ailleurs en Europe continentale, caractérise l'art sous les règnes de Louis XVIII et de son frère Charles X. L'état des finances ne permet pas de grandes dépenses."},
        {date: '1830/1850', name: 'Style Louis Philippe', link: 'louis-philippe', subtitle: "Règne de Louis Philippe (1830 - 1848)", short: "Le style Louis-Philippe est un style de mobilier français en vogue sous le règne de Louis-Philippe (1830-1848) qui influence aussi l'architecture. C'est un style de bourgeois affairés et cossus, partagés entre le souci de leur confort et le désir de se donner des lettres de noblesse."},
        {date: '1850/1890', name: 'Style Napoléon III', link: 'napoleon-III', subtitle: "Règne de Napoléon III (1848 - 1890)", short: "Le style Second Empire, dit aussi style Napoléon III, est un style architectural, d'ameublement, d'arts décoratifs et vestimentaire, né en France durant le Second Empire, sous l'impulsion de l' empereur Napoléon III et de l' impératrice Eugénie."},
        {date: '1890/1914', name: 'Style Art Nouveau', link: 'art-nouveau', subtitle: "Mouvement artistique de la fin du XIXe et du début du XXe siècle qui s'appuie sur l'esthétique des lignes courbes.", short: "L'Art nouveau est un mouvement artistique de la fin du XIXᵉ et du début du XXᵉ siècle qui s'appuie sur l'esthétique des lignes courbes. Il met en avant les motifs floraux. Né en réaction contre les dérives de l'industrialisation et la reproduction des anciens styles, c'est un mouvement soudain et rapide qui connaît un développement international."},
        {date: '1920/1939', name: 'Style Art Déco', link: 'art-deco', subtitle: "Abréviation de « Arts décoratifs », mouvement artistique d'architecture-décoration de portée mondiale, de 1920 à 1939.", short: "L'Art déco est un mouvement artistique de portée mondiale né progressivement dans les années 1910 et qui prend son plein épanouissement au cours des années 1920, avant de décliner lentement à partir des années 1930. Il embrasse l'ensemble des activités artistiques et les métiers d'art. Le « style Art déco » tire son nom de l'Exposition internationale des arts décoratifs et industriels modernes qui se tint à Paris en 1925."},
        {date: '1930/1960', name: 'Fonctionnalisme', link: 'fonctionnalisme', subtitle: "Marqué soit par la pérennité du classique, soit pas le fonctionnalisme lié à la production en série.", short: "En architecture, le fonctionnalisme est un principe selon lequel la forme des bâtiments doit être exclusivement l'expression de leur usage. Cette formulation n'est pas si évidente à définir, car elle est matière à confusion et à controverse à l'intérieur de la profession, particulièrement en ce qui concerne le Mouvement moderne."},
        {date: '1929', name: 'Design', link: 'design', subtitle: "Historiquement le « design » serait dû à la crise de 1929.", short: "Face à la baisse dramatique de la consommation, les industriels font appel, sur avis des publicitaires, aux artistes commerciaux pour tenter de stimuler les ventes. Déjà l’automobile avait ressenti le besoin de se distinguer de la concurrence par l’image, jusqu’alors ignorée par les fabricants. Exemple avec la « Ford T » qui, constamment améliorée sur le plan technique, gardait sensiblement le même aspect extérieur. « N’importe quelle couleur, pourvu qu’elle soit noire ! » disait Henri Ford."},
    ]

    return (
        <div className="page_layer">
            <h1 className="page_title">Histoire de l'Art</h1>
            <ul class="timeline">
                {events.map((event, index) => 
                    <li class="timeline-event" key={index}>
                        <label class="timeline-event-icon"></label>
                        <div class="timeline-event-copy">
                            <p class="timeline-event-thumbnail"><Link to={event.link} className="event-link">{event.date}</Link></p>
                            <h2>{event.name}</h2>
                            <h3>{event.subtitle}</h3>
                            <p className="short">{event.short}</p>
                        </div>
                    </li>
                )}
            </ul>
        </div>
    )
}

export default HistoireDeLart
